"""Dhan instrument-master loader.

Turns Dhan's public scrip-master CSV into everything the live/paper-live feed
needs and that main.py previously left as TODOs:

  - the NIFTY current-month FUT  -> the pricing underlying F. Per black76.py's
    contract, the whole system prices/deltas off the FUTURE, never cash spot,
    so the underlying we subscribe to is FUTIDX, not the NIFTY 50 index.
  - the option chain (CE/PE) for a chosen weekly expiry, windowed around ATM.
  - security_id <-> (strike, opt_type) maps for (a) remapping raw ticks, which
    carry only security_id + LTP, and (b) resolving a Leg to a security_id when
    placing orders.

Column layout is verified against the real header of
api-scrip-master-detailed.csv:
  EXCH_ID, SEGMENT, SECURITY_ID, ISIN, INSTRUMENT, UNDERLYING_SECURITY_ID,
  UNDERLYING_SYMBOL, SYMBOL_NAME, DISPLAY_NAME, INSTRUMENT_TYPE, SERIES,
  LOT_SIZE, SM_EXPIRY_DATE, STRIKE_PRICE, OPTION_TYPE, TICK_SIZE, ...

Real rows observed:
  index : EXCH_ID=NSE SEGMENT=I  SECURITY_ID=13 SYMBOL_NAME=NIFTY INSTRUMENT_TYPE=INDEX
  option: EXCH_ID=NSE SEGMENT=D  INSTRUMENT=OPTIDX UNDERLYING_SYMBOL=NIFTY
          SM_EXPIRY_DATE=YYYY-MM-DD STRIKE_PRICE=29300.00000 OPTION_TYPE=CE|PE LOT_SIZE=65
  future: EXCH_ID=NSE SEGMENT=D  INSTRUMENT=FUTIDX UNDERLYING_SYMBOL=NIFTY
          SM_EXPIRY_DATE=YYYY-MM-DD (monthly)
"""
from __future__ import annotations

import csv
import time
import urllib.request
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path
from typing import Optional

# Dhan publishes this without auth. Detailed variant carries UNDERLYING_SYMBOL +
# INSTRUMENT which we rely on to disambiguate FUTIDX/OPTIDX from equity F&O.
MASTER_URL = "https://images.dhan.co/api-data/api-scrip-master-detailed.csv"
MASTER_PATH = Path(__file__).parent / "runtime" / "api-scrip-master-detailed.csv"

# CE/PE in the master vs the CALL/PUT the strategy/greeks use everywhere else.
_OT = {"CE": "CALL", "PE": "PUT"}

# SEGMENT letter in the master -> the string key DhanFeed maps to a MarketFeed
# exchange-segment constant. Kept as strings so this module never imports dhanhq
# (must stay importable for the offline self-test and pure paper dev).
SEGMENT_KEY = {"I": "IDX_I", "D": "NSE_FNO", "E": "NSE_EQ"}


@dataclass
class OptionRow:
    security_id: str
    strike: float
    opt_type: str          # "CALL" | "PUT"
    segment_key: str       # "NSE_FNO"


@dataclass
class Universe:
    """Everything startup wiring needs, all derived from one CSV parse."""
    underlying_security_id: str          # NIFTY current-month FUT
    underlying_segment_key: str
    expiry: date                         # chosen weekly OPTION expiry
    lot_size: int                        # from the master, NOT a hardcoded const
    options: list[OptionRow] = field(default_factory=list)

    # secid -> (strike, "CALL"|"PUT"): remap a raw tick into the chain.
    secid_to_option: dict = field(default_factory=dict)
    # (strike, "CALL"|"PUT") -> secid: resolve a Leg when placing an order.
    option_to_secid: dict = field(default_factory=dict)

    def subscription_list(self) -> list[tuple]:
        """(segment_key, security_id) tuples for the FUT underlying + every
        option strike. DhanFeed turns each into a Quote subscription."""
        subs = [(self.underlying_segment_key, self.underlying_security_id)]
        subs += [(o.segment_key, o.security_id) for o in self.options]
        return subs


def download_master(path: Path = MASTER_PATH, max_age_s: float = 12 * 3600) -> Path:
    """Download the scrip master if missing or older than max_age_s. The master
    is regenerated by Dhan daily; a same-day cached copy is fine."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fresh = path.exists() and (time.time() - path.stat().st_mtime) < max_age_s
    if not fresh:
        tmp = path.with_suffix(path.suffix + ".tmp")
        urllib.request.urlretrieve(MASTER_URL, tmp)
        tmp.replace(path)
    return path


def _pick_expiry(expiries: set[date], on: date, prefer: Optional[date]) -> date:
    """If prefer is given and tradeable, use it. Otherwise the nearest expiry on
    or after `on` (the current weekly); falls back to the latest past expiry only
    if the master somehow has nothing forward-dated."""
    if prefer is not None and prefer in expiries:
        return prefer
    future = sorted(e for e in expiries if e >= on)
    if future:
        return future[0]
    return max(expiries)


def load_universe(
    path: Path = MASTER_PATH,
    underlying: str = "NIFTY",
    now: Optional[datetime] = None,
    prefer_expiry: Optional[date] = None,
    spot_hint: Optional[float] = None,
    strike_window: int = 40,
) -> Universe:
    """Parse the master into a Universe.

    spot_hint + strike_window bound the chain we subscribe to: only strikes
    within `strike_window` steps of the ATM (nearest strike to spot_hint) are
    included, so a normal day is ~2*window*2 instruments instead of the whole
    several-hundred-strike board. If spot_hint is None, ALL strikes of the
    chosen expiry are included (correct but heavy -- pass a hint).
    """
    now = now or datetime.now()
    today = now.date()

    fut_rows: list[tuple[date, str, str]] = []   # (expiry, secid, segment_key)
    opt_by_expiry: dict[date, list[OptionRow]] = {}
    lot_by_expiry: dict[date, int] = {}

    with open(path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            if row.get("EXCH_ID") != "NSE":
                continue
            if row.get("UNDERLYING_SYMBOL") != underlying:
                continue
            instrument = row.get("INSTRUMENT")
            seg_key = SEGMENT_KEY.get(row.get("SEGMENT", ""))
            if seg_key is None:
                continue
            exp_raw = (row.get("SM_EXPIRY_DATE") or "").strip()
            if not exp_raw:
                continue
            try:
                exp = datetime.strptime(exp_raw[:10], "%Y-%m-%d").date()
            except ValueError:
                continue

            if instrument == "FUTIDX":
                fut_rows.append((exp, row["SECURITY_ID"], seg_key))
            elif instrument == "OPTIDX":
                ot = _OT.get((row.get("OPTION_TYPE") or "").strip())
                if ot is None:
                    continue
                try:
                    strike = float(row["STRIKE_PRICE"])
                except (ValueError, KeyError):
                    continue
                opt_by_expiry.setdefault(exp, []).append(
                    OptionRow(row["SECURITY_ID"], strike, ot, seg_key)
                )
                try:
                    lot_by_expiry[exp] = int(float(row["LOT_SIZE"]))
                except (ValueError, KeyError):
                    pass

    if not fut_rows:
        raise RuntimeError(f"{underlying}: no FUTIDX rows in master {path} -- wrong file or symbol?")
    if not opt_by_expiry:
        raise RuntimeError(f"{underlying}: no OPTIDX rows in master {path} -- wrong file or symbol?")

    expiry = _pick_expiry(set(opt_by_expiry), today, prefer_expiry)
    options = opt_by_expiry[expiry]
    lot_size = lot_by_expiry.get(expiry, 0)
    if lot_size <= 0:
        raise RuntimeError(f"{underlying} {expiry}: master has non-positive lot size {lot_size!r}")

    # Current-month FUT = nearest FUT expiry on/after today (fallback: nearest overall).
    fut_future = sorted(f for f in fut_rows if f[0] >= today) or sorted(fut_rows)
    _, fut_secid, fut_seg = fut_future[0]

    if spot_hint is not None and options:
        strikes = sorted({o.strike for o in options})
        atm = min(strikes, key=lambda s: abs(s - spot_hint))
        i = strikes.index(atm)
        lo, hi = strikes[max(0, i - strike_window)], strikes[min(len(strikes) - 1, i + strike_window)]
        options = [o for o in options if lo <= o.strike <= hi]

    uni = Universe(
        underlying_security_id=fut_secid,
        underlying_segment_key=fut_seg,
        expiry=expiry,
        lot_size=lot_size,
        options=options,
    )
    for o in options:
        uni.secid_to_option[o.security_id] = (o.strike, o.opt_type)
        uni.option_to_secid[(o.strike, o.opt_type)] = o.security_id
    return uni


def _find_close(obj, sid: int):
    """Walk a nested Dhan quote/ohlc response for this security's OHLC close.
    Response nesting varies across dhanhq point releases, so we search rather
    than hard-code a path: find the dict keyed by this secid, then its ohlc.close
    (falls back to a bare 'close' / 'prev_close')."""
    target = None

    def walk(o):
        nonlocal target
        if target is not None:
            return
        if isinstance(o, dict):
            for k in (str(sid), sid):
                if k in o and isinstance(o[k], dict):
                    node = o[k]
                    ohlc = node.get("ohlc") if isinstance(node.get("ohlc"), dict) else node
                    for ck in ("close", "prev_close", "previous_close"):
                        if ck in ohlc and ohlc[ck] not in (None, 0, "0"):
                            target = float(ohlc[ck])
                            return
            for v in o.values():
                walk(v)
        elif isinstance(o, list):
            for v in o:
                walk(v)

    walk(obj)
    return target


def fetch_prev_close(client_id: str, access_token: str, security_id: str,
                     segment_key: str = "NSE_FNO", retries: int = 4,
                     backoff: float = 0.75):
    """Previous-day close for one instrument via Dhan's REST market-quote API,
    so the runtime (which holds the token) fetches it -- no manual entry.

    Defensive by design: tries the quote then ohlc method, searches the response
    for the close, and returns None on any failure so the caller can fall back
    to a manual override rather than crash. Method/field names can drift between
    dhanhq releases; preflight prints the result so it's eyeballed before trading.

    Retries the whole quote/ohlc sweep with exponential backoff: when several
    books launch at once (run_all.py) their simultaneous quote calls can trip
    Dhan's rate limiter and one comes back empty. A single throttled response
    must not sink a book's whole session, so we retry (with jitter) before
    giving up and returning None.
    """
    import random
    import time as _time
    from dhanhq import DhanContext, dhanhq  # guarded: live/paper-live only
    ctx = DhanContext(client_id, access_token)
    dhan = dhanhq(ctx)
    sid = int(security_id)
    securities = {segment_key: [sid]}
    for attempt in range(max(1, retries)):
        for meth in ("quote_data", "ohlc_data"):
            fn = getattr(dhan, meth, None)
            if fn is None:
                continue
            try:
                try:
                    resp = fn(securities=securities)
                except TypeError:
                    resp = fn(securities)
            except Exception:
                continue
            close = _find_close(resp, sid)
            if close:
                return close
        # nothing usable this sweep -- wait (with jitter) and retry, unless last
        if attempt < max(1, retries) - 1:
            _time.sleep(backoff * (2 ** attempt) + random.uniform(0, backoff))
    return None


if __name__ == "__main__":
    # Offline self-test against a locally cached master (does NOT hit the network
    # unless the file is missing/stale). Verifies the parse shape only.
    download_master()
    uni = load_universe(spot_hint=None)
    print(f"underlying FUT secid={uni.underlying_security_id} seg={uni.underlying_segment_key}")
    print(f"chosen expiry={uni.expiry}  lot_size={uni.lot_size}  #strikes(both sides)={len(uni.options)}")
    calls = sorted(o.strike for o in uni.options if o.opt_type == "CALL")
    puts = sorted(o.strike for o in uni.options if o.opt_type == "PUT")
    print(f"CALL strikes {len(calls)}: {calls[0]} .. {calls[-1]}")
    print(f"PUT  strikes {len(puts)}: {puts[0]} .. {puts[-1]}")
    assert calls == puts, "CE/PE strike sets differ -- chain is asymmetric"
    # windowing sanity
    mid = calls[len(calls) // 2]
    w = load_universe(spot_hint=mid, strike_window=10)
    ws = sorted({o.strike for o in w.options})
    assert len(ws) <= 21, f"window too wide: {len(ws)} strikes"
    assert w.secid_to_option and w.option_to_secid, "maps not built"
    print(f"windowed(+-10 @ {mid}): {len(ws)} strikes {ws[0]}..{ws[-1]}  maps={len(w.secid_to_option)}")
    print("PASS")
