"""Live "what would this strategy do TODAY" suggestions for the four curated
options strategies shown on options_strategies.html.

The strategy parameters here are copied VERBATIM from the backtest definitions
so the live suggestion matches what was actually tested:

  - IC-1pct-manage50            iron_condor.py     ICStrategy(0.010, 0.008, entry_offset_days=2, target_frac=0.50, sl_mult=2.0)
  - Momentum-Expiry-HoldToSettle backtest.py       Strategy("momentum3", 0.012, 0.008, entry_offset_days=2)  held to settlement
  - MeanReversion-Expiry         backtest.py       Strategy("mean_rev", 0.015, 0.010, sl_mult=1.5, target_frac=0.6, entry_offset_days=2)
  - FlowExpiry-pcr-Medium        round3_followups  sig_pcr (hi=1.3, lo=0.7) x (0.012, 0.008), sl_mult=1.5, target_frac=0.6

Signals (same maths as backtest.py / zen_sweep.py, computed on live data):
  momentum3: 3-day close return, deadband 0.0005 -> bull/bear/skip
  mean_rev : 1-day close return, fade moves > 0.6% (rally -> bear, drop -> bull)
  pcr      : chain-wide put OI / call OI; > 1.3 crowded puts -> bull, < 0.7 -> bear
  IC       : non-directional, always quotes both sides.

Spread construction mirrors backtest.py build_spread():
  bull -> put credit spread BELOW spot  (short spot*(1-otm), long spot*(1-otm-wing))
  bear -> call credit spread ABOVE spot (short spot*(1+otm), long spot*(1+otm+wing))
  IC   -> both a call spread above and a put spread below.

GET /api/options_strategies?symbol=NIFTY
Serves suggestions only; the page reads backtest stats from the static
data/options_strategies.json (regenerated by options_backtest/scripts/export_web_json.py).
"""
from __future__ import annotations

import datetime as dt
import json
import sys
from http.server import BaseHTTPRequestHandler
from pathlib import Path
from urllib.parse import parse_qs, urlparse

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from api.options_chain import (  # noqa: E402
    ConfigError, ProviderError, SymbolNotFoundError,
    fetch_expiry_list, fetch_option_chain, _load_env_file,
)
from api.index_ohlc import fetch_index_ohlc  # noqa: E402

# Backtests ran on NIFTY bhavcopy data; other indices reuse the same params
# but are flagged so the UI can say "parameters tuned on NIFTY".
YAHOO_INDEX = {"NIFTY": "^NSEI", "BANKNIFTY": "^NSEBANK", "SENSEX": "^BSESN"}
BACKTESTED_SYMBOLS = {"NIFTY"}

MOMENTUM_LOOKBACK = 3      # backtest.py sig_momentum(lookback=3)
MOMENTUM_DEADBAND = 0.0005
MEANREV_THRESH = 0.006     # backtest.py sig_mean_reversion(lookback=1, thresh=0.006)
PCR_HI, PCR_LO = 1.3, 0.7  # zen_sweep.py sig_pcr

STRATEGIES = [
    # name, kind, signal, short_otm_pct, wing_pct, sl_mult, target_frac, exit_note
    {"name": "IC-1pct-manage50", "kind": "iron_condor", "signal": "always",
     "otm": 0.010, "wing": 0.008, "sl_mult": 2.0, "target_frac": 0.50,
     "exit_note": "Exit at 50% of credit captured; stop at 2x credit."},
    {"name": "Momentum-Expiry-HoldToSettle", "kind": "credit_spread", "signal": "momentum3",
     "otm": 0.012, "wing": 0.008, "sl_mult": None, "target_frac": None,
     "exit_note": "Held to settlement -- no early exit in the backtest."},
    {"name": "MeanReversion-Expiry", "kind": "credit_spread", "signal": "mean_rev",
     "otm": 0.015, "wing": 0.010, "sl_mult": 1.5, "target_frac": 0.6,
     "exit_note": "EOD checks: take profit at 60% of credit, stop at 1.5x credit."},
    {"name": "FlowExpiry-pcr-Medium", "kind": "credit_spread", "signal": "pcr",
     "otm": 0.012, "wing": 0.008, "sl_mult": 1.5, "target_frac": 0.6,
     "exit_note": "EOD checks: take profit at 60% of credit, stop at 1.5x credit."},
]
ENTRY_OFFSET_DAYS = 2  # all four enter 2 trading days before expiry


# --- signals -----------------------------------------------------------------
def _sig_momentum(closes: list[float]) -> tuple[str, str]:
    if len(closes) < MOMENTUM_LOOKBACK + 1:
        return "skip", "not enough index history"
    ret = closes[-1] / closes[-1 - MOMENTUM_LOOKBACK] - 1
    label = f"{MOMENTUM_LOOKBACK}-day return {ret * 100:+.2f}%"
    if ret > MOMENTUM_DEADBAND:
        return "bull", label + " -> ride the trend (sell puts below)"
    if ret < -MOMENTUM_DEADBAND:
        return "bear", label + " -> ride the trend (sell calls above)"
    return "skip", label + " -> inside deadband, no edge today"


def _sig_mean_rev(closes: list[float]) -> tuple[str, str]:
    if len(closes) < 2:
        return "skip", "not enough index history"
    ret = closes[-1] / closes[-2] - 1
    label = f"1-day return {ret * 100:+.2f}%"
    if ret > MEANREV_THRESH:
        return "bear", label + " -> fade the rally (sell calls above)"
    if ret < -MEANREV_THRESH:
        return "bull", label + " -> fade the drop (sell puts below)"
    return "skip", label + f" -> move under {MEANREV_THRESH * 100:.1f}%, nothing to fade"


def _sig_pcr(pcr: float | None) -> tuple[str, str]:
    if pcr is None:
        return "skip", "chain OI unavailable, cannot compute PCR"
    label = f"put/call OI ratio {pcr:.2f}"
    if pcr > PCR_HI:
        return "bull", label + f" > {PCR_HI} -> crowded puts, contrarian bounce (sell puts)"
    if pcr < PCR_LO:
        return "bear", label + f" < {PCR_LO} -> crowded calls, contrarian fade (sell calls)"
    return "skip", label + f" -> between {PCR_LO} and {PCR_HI}, no sentiment extreme"


# --- strike/premium helpers --------------------------------------------------
def _chain_rows(chain: dict) -> tuple[float, dict[float, dict]]:
    """Return (spot, {strike: {"ce": leg, "pe": leg}}) from fetch_option_chain(),
    whose shape is {"spot": float, "strikes": [{"strike", "ce", "pe"}, ...]}."""
    spot = float(chain.get("spot") or 0)
    rows: dict[float, dict] = {}
    for s in chain.get("strikes") or []:
        try:
            rows[float(s["strike"])] = s
        except (KeyError, TypeError, ValueError):
            continue
    return spot, rows


def _leg_price(rows: dict[float, dict], strike: float, opt_type: str) -> float | None:
    leg = (rows.get(strike) or {}).get(opt_type.lower()) or {}
    try:
        px = float(leg.get("ltp") or 0)
    except (TypeError, ValueError):
        return None
    return px if px > 0 else None


def _nearest_tradable(rows: dict[float, dict], target: float, opt_type: str) -> float | None:
    """Nearest listed strike to target whose leg actually has a live price."""
    for strike in sorted(rows, key=lambda s: abs(s - target)):
        if _leg_price(rows, strike, opt_type) is not None:
            return strike
    return None


def _build_side(rows: dict[float, dict], spot: float, direction: str,
                otm: float, wing: float) -> dict | None:
    """One credit-spread side, mirroring backtest.py build_spread()."""
    if direction == "bull":
        opt_type, s_target, l_target = "pe", spot * (1 - otm), spot * (1 - otm - wing)
    else:
        opt_type, s_target, l_target = "ce", spot * (1 + otm), spot * (1 + otm + wing)
    short = _nearest_tradable(rows, s_target, opt_type)
    long = _nearest_tradable(rows, l_target, opt_type)
    if short is None or long is None or short == long:
        return None
    short_px = _leg_price(rows, short, opt_type)
    long_px = _leg_price(rows, long, opt_type)
    if short_px is None or long_px is None:
        return None
    credit = short_px - long_px
    if credit <= 0:
        return None
    return {
        "type": opt_type.upper(),
        "legs": [
            {"action": "SELL", "type": opt_type.upper(), "strike": short, "ltp": round(short_px, 2)},
            {"action": "BUY", "type": opt_type.upper(), "strike": long, "ltp": round(long_px, 2)},
        ],
        "credit": credit,
        "wing_points": abs(short - long),
    }


def _pcr_from_chain(rows: dict[float, dict]) -> float | None:
    ce_oi = pe_oi = 0.0
    for v in rows.values():
        try:
            ce_oi += float((v.get("ce") or {}).get("oi") or 0)
            pe_oi += float((v.get("pe") or {}).get("oi") or 0)
        except (TypeError, ValueError):
            continue
    return round(pe_oi / ce_oi, 3) if ce_oi > 0 else None


def _money(spread_sides: list[dict], lot: int | None, sl_mult, target_frac) -> dict:
    credit = sum(s["credit"] for s in spread_sides)
    max_wing = max(s["wing_points"] for s in spread_sides)
    max_loss = max_wing - credit
    out = {
        "credit_points": round(credit, 2),
        "max_loss_points": round(max_loss, 2),
        "reward_risk": round(credit / max_loss, 2) if max_loss > 0 else None,
        "target_exit_points": round(credit * target_frac, 2) if target_frac else None,
        # sl_mult means "exit when debit-to-close = sl_mult x credit received".
        # Net loss at that point is (sl_mult - 1) x credit, NOT sl_mult x credit,
        # since the credit already collected offsets part of the buy-back cost.
        # Clamp to max_loss since a defined-risk spread can never lose more than that.
        "stop_loss_points": round(min(credit * (sl_mult - 1), max_loss), 2) if sl_mult else None,
    }
    if lot:
        out["lot_size"] = lot
        out["credit_per_lot_rs"] = round(credit * lot)
        out["max_loss_per_lot_rs"] = round(max_loss * lot)
    return out


def _breakevens(spread_sides: list[dict], credit: float) -> list[float]:
    bes = []
    for s in spread_sides:
        short = s["legs"][0]["strike"]
        bes.append(round(short + credit, 2) if s["type"] == "CE" else round(short - credit, 2))
    return sorted(bes)


# --- main --------------------------------------------------------------------
def build_suggestions(symbol: str) -> dict:
    symbol = symbol.upper()
    exp = fetch_expiry_list(symbol)
    expiries = exp.get("expiries") or []
    if not expiries:
        raise ProviderError(f"no expiries returned for {symbol}")
    expiry = expiries[0]
    lot = exp.get("lot_size")

    chain_resp = fetch_option_chain(symbol, expiry)
    spot, rows = _chain_rows(chain_resp)
    if spot <= 0 or not rows:
        raise ProviderError(f"empty option chain for {symbol} {expiry}")

    closes: list[float] = []
    yahoo = YAHOO_INDEX.get(symbol)
    if yahoo:
        ohlc = fetch_index_ohlc(yahoo)
        if ohlc:
            closes = [bar[4] for bar in ohlc["bars"]]
    pcr = _pcr_from_chain(rows)

    try:
        dte = (dt.date.fromisoformat(expiry[:10]) - dt.date.today()).days
    except ValueError:
        dte = None
    # Backtest enters exactly 2 trading days pre-expiry; live approximation:
    # flag "in window" when expiry is 1-4 calendar days out.
    in_window = dte is not None and 1 <= dte <= ENTRY_OFFSET_DAYS + 2

    suggestions = []
    for strat in STRATEGIES:
        if strat["signal"] == "momentum3":
            direction, why = _sig_momentum(closes)
        elif strat["signal"] == "mean_rev":
            direction, why = _sig_mean_rev(closes)
        elif strat["signal"] == "pcr":
            direction, why = _sig_pcr(pcr)
        else:
            direction, why = "both", "non-directional: sells a call spread AND a put spread"

        item = {
            "name": strat["name"],
            "kind": strat["kind"],
            "signal": strat["signal"],
            "direction": direction,
            "why": why,
            "exit_note": strat["exit_note"],
            "entry_rule": f"Backtest entered {ENTRY_OFFSET_DAYS} trading days before expiry.",
        }
        if direction == "skip":
            item["status"] = "no_trade"
            suggestions.append(item)
            continue

        if direction == "both":
            sides = [_build_side(rows, spot, d, strat["otm"], strat["wing"]) for d in ("bull", "bear")]
        else:
            sides = [_build_side(rows, spot, direction, strat["otm"], strat["wing"])]
        sides = [s for s in sides if s]
        if not sides or (direction == "both" and len(sides) < 2):
            item["status"] = "no_quote"
            item["why"] = "could not find tradable strikes with live premiums"
            suggestions.append(item)
            continue

        money = _money(sides, lot, strat["sl_mult"], strat["target_frac"])
        item.update({
            "status": "trade",
            "legs": [leg for s in sides for leg in s["legs"]],
            "breakevens": _breakevens(sides, money["credit_points"]),
            **money,
        })
        suggestions.append(item)

    return {
        "source": chain_resp.get("source", "live"),
        "demo_reason": chain_resp.get("demo_reason"),
        "symbol": symbol,
        "backtested_on": symbol in BACKTESTED_SYMBOLS,
        "spot": round(spot, 2),
        "expiry": expiry,
        "days_to_expiry": dte,
        "in_entry_window": in_window,
        "pcr": pcr,
        "lot_size": lot,
        "suggestions": suggestions,
    }


class handler(BaseHTTPRequestHandler):
    def _cors(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def _send_json(self, status: int, obj):
        body = json.dumps(obj).encode("utf-8")
        self.send_response(status)
        self._cors()
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self._cors()
        self.end_headers()

    def do_GET(self):
        qs = parse_qs(urlparse(self.path).query)
        symbol = (qs.get("symbol") or ["NIFTY"])[0].strip().upper()
        try:
            self._send_json(200, build_suggestions(symbol))
        except SymbolNotFoundError as exc:
            self._send_json(404, {"error": str(exc)})
        except (ValueError, TypeError) as exc:
            self._send_json(400, {"error": str(exc)})
        except ConfigError as exc:
            self._send_json(500, {"error": str(exc)})
        except ProviderError as exc:
            self._send_json(502, {"error": str(exc)})
        except Exception as exc:  # noqa: BLE001 -- never leak a stack trace to the page
            self._send_json(500, {"error": str(exc)})


if __name__ == "__main__":
    _load_env_file()
    print(json.dumps(build_suggestions(sys.argv[1] if len(sys.argv) > 1 else "NIFTY"), indent=2))
